#!/bin/bash
if ps -ef | grep -v grep | grep -q rhythmbox
then 
	artist=`rhythmbox-client --print-playing-format %ta`
	album=`rhythmbox-client --print-playing-format %aa`
	str="`echo "$artist $album" | sed -e s/\\ /+/g`"
	art=`wget "http://www.albumart.org/index.php?skey=$str&itempage=1&newsearch=1&searchindex=Music" -q -O - | grep "http://www.albumart.org/images/zoom-icon.jpg" -m 1 | sed -e 's/" border="0" class="image_border.*//' | sed -e 's/.*img src="//'`
	wget $art -q -O /home/rd/album.jpg; mv ~/album.jpg ~/.album.jpg && chmod 777 ~/.album.jpg
fi
